### PR TITLE
adding placement grading pie charts to player detail view

### PR DESCRIPTION
**Pull request by EcZachly**
I'd love feedback on this @fjaxyu  and @bbleaptrot 

This is live at www.brshooter.com/gamer/EcZachly 

I added a big tabs menu. This shows how many A, B, C, D, and F graded games each player has in Solo, Duo, Trio and Quads. 

The grading right now is based solely on placement.

### CODE REVIEW

**Comment by fjaxyu** [comment]
Screen Shot 2020-09-17 at 4 09 34 PM

I'm getting nothing

**Comment by EcZachly** [comment]
Tap the tabs bro

**Comment by fjaxyu** [comment]
Ooooh, nice! Open the first one by default when the page loads and I think this is great! Nice work!

**Comment by EcZachly** [comment]
Cool. I'm merging this PR. I made it so the KDR page is the default view when opening the detail.

**Comment by fjaxyu** [comment]
Perfect! Looks great!

**Pull request merged**
